### PR TITLE
MET-1460 user cannot populate metadata

### PR DESCRIPTION
**Pull request by musketyr**
make UniqueChecker proof to working with not-yet-saved DataModel

### CODE REVIEW

**Comment by musketyr** [comment]
@amilward @passionfruit18 can anyone of you do a code review?

**Comment by passionfruit18** [comment]
Don't really understand what is going on?

**Comment by musketyr** [comment]
As this might be called on not-yet-saved instance `model` was not properly saved is some use cases causing problems with `criteria.list()` method. The quries happen in separate session (see `withNewSessio` call where `model` might not exist yet. `dataModel` is using `load` method so it is just a proxy with type and `id`.  `HibernateHelper.ensureNoProxy(dataModel)` ensures the proxy is unwrapped to normal object with all the properties loaded so the `toString()` method returns meaningfull text.

**Comment by passionfruit18** [comment]
OK so where does all this fit into the grails application flow? When the application tries to save edited data to the database it must go through these convention checkers? Where are these convention checkers used?

And what is `criteria.list()` method?

**Comment by musketyr** [comment]
The checkers (including `UniqueChecker`) are called from couple of places

- from `AbstractRestfulController` and `AbstractCatalogueElementController` on save or update (see calls of `validatePolicies` method)
- from `ElementService` when the data model is finalized they are called from within `checkFinalizeEligibility` method of `DataModel`

`criteria.list()` method returns the list of the results of the database query specified by given criteria object.

**Pull request merged**
