### PR TITLE
Implement ValidateValueAgainstDataTypeSpec

### PR DESCRIPTION
**Pull request by sdelamo**
See https://github.com/MetadataConsulting/ModelCataloguePlugin/issues/1195

### CODE REVIEW

**Comment by sdelamo** [comment]
We should create a separate Geb Page for `DataTypeValueValidatePage` instead of placing the logic in `DataTypePage`.

Test is failing for me too. 

Could you address both ?

**Comment by vijayshukla30** [comment]
@sdelamo 
Implemented and pushed you can check and let me know if it doesn't work

**Comment by sdelamo** [comment]
I have done some commits. Please @Vendetta30 check them out. 

Note I am still getting failures. 

We should strive to avoid using sleep statements and use Geb waiting capability instead. 

http://www.gebish.org/manual/current/#waiting

**Comment by vijayshukla30** [comment]
@sdelamo 
Done, as suggested

**Pull request merged**
