### PR TITLE
Met 1218 catalogue id move

### PR DESCRIPTION
**Pull request by kuceram**

### CODE REVIEW

**Comment by kuceram** [comment]
Tests fails due to Saxon library cannot be loaded, server returns 404. I've founded that you've moved the Saxon lib within this pull request https://github.com/MetadataConsulting/ModelCataloguePlugin/commit/5546d304b873c1647516458c6afc5f7531f75988

Can you look at why it is not loaded. Even if I run it in local dev mode, this file is not served...

005-001-xml editor-failure

**Comment by musketyr** [comment]
This shouldn't be problem. It fails only in dev when not running from war. If you move it to assets it adds about 5 minutes to assets compilation.

**Comment by kuceram** [comment]
I don't get it. If it fails in dev, it is a problem... I don't understand the second sentence... :-(

**Comment by kuceram** [comment]
@musketyr wait with merge, please...

**Comment by kuceram** [comment]
@musketyr ok, ready for merge! When tests pass...

**Comment by kuceram** [comment]
@musketyr ready to be merged 🐕

**Comment by kuceram** [comment]
@musketyr Can you merge this? 🕦

**Pull request merged**
