### PR TITLE
Check "Suite A" functional tests

### PR DESCRIPTION
**Pull request by passionfruit18**
Making pull request to check which functional tests from suiteA work

### CODE REVIEW

**Comment by passionfruit18** [comment]
UnIgnored all classes.

6/10 tests pass.

AssetWizardSpec and DataModelWizardSpec pass, but there are a lot of ignored methods.

BatchAndActionsSpec, ChangesSpec, DataClassWizardSpec, DataElementWizardSpec fail.

But there are 13 specs.

The following didn't run at all:

ChangeLogForEligibilitySpec, DataTypeWizardSpec, SearchFunctionalSpec. All of their methods are ignored.

**Comment by passionfruit18** [comment]
Unignored all methods in AssetWizardSpec and DataModelWizardSpec.

They failed.

**Comment by passionfruit18** [comment]
Unignored all methods in ChangeLogForEligibilitySpec, DataTypeWizardSpec, SearchFunctionalSpec. They failed.

So the following fail:
AssetWizardSpec and DataModelWizardSpec 
BatchAndActionsSpec, ChangesSpec, DataClassWizardSpec, DataElementWizardSpec fail.
ChangeLogForEligibilitySpec, DataTypeWizardSpec, SearchFunctionalSpec

**Comment by passionfruit18** [comment]
Ignored just the failing tests so that the whole suite passes for now.

**Review by davidmilward — APPROVED** [review]

**Pull request merged**
